[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = ["python -m ensurepip --upgrade", "python -m pip install -r requirements.txt"]

[start]
cmd = "python -m gunicorn -k gevent -w 1 -b 0.0.0.0:$PORT 'backend.app:create_app()'"
